import NavBar from '@/components/NavBar'
import './globals.css'
import type { Metadata } from 'next'
import { Outfit, Truculenta } from 'next/font/google'

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-out',
})

const truculenta = Truculenta({
  subsets: ['latin'],
  variable: '--font-truco',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${outfit.className} ${truculenta.className} font-sans`}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
